// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;
using NomadCode.UIExtensions;

namespace Archives
{
	public partial class ColbyTableViewController : UITableViewController
	{

        List<string> Items { get; set; }

		public ColbyTableViewController (IntPtr handle) : base (handle)
		{
		}

        public override nint NumberOfSections(UITableView tableView) => 1;

        public override nint RowsInSection(UITableView tableView, nint section) => Items.Count;


        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.Dequeue<ColbyTableViewCell>(indexPath);

            var item = Items[indexPath.Row];

            cell.AccessoryView.Tag = indexPath.Row;

            cell.TextLabel.Text = item;

            return cell;
        }


        partial void cellSwitchChanged(NSObject sender)
        {
            if (sender is UISwitch s)
            {
                var index = s.Tag;

                var item = Items[(int)index];
            }
        }
	}
}
