// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Archives
{
	public partial class ColbyTableViewCell : UITableViewCell
	{
		public ColbyTableViewCell (IntPtr handle) : base (handle)
		{
		}

        public override UITableViewCellAccessory Accessory
        {
            get
            {
                return base.Accessory;
            }
            set
            {
                base.Accessory = value;
            }
        }
	}
}
