// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Archives
{
	public partial class RobertoTableViewCell : UITableViewCell
	{
		public RobertoTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
