// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Archives.TableViewCells
{
	public partial class SecurityTableViewCell : UITableViewCell
	{
		public SecurityTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
