// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Archives.ViewControllers
{
	public partial class AboutViewController : UIViewController
	{
		public AboutViewController (IntPtr handle) : base (handle) { }

		public override void ViewDidLoad()
		{
			Foundation.NSUrl url = new Foundation.NSUrl("http://rcervantes.me/");
			webView.LoadRequest(new Foundation.NSUrlRequest(url));
			webView.ScalesPageToFit = true;
		}
	}
}
