// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Archives.ViewControllers
{
	public partial class ArchivesViewController : UITableViewController
	{
		public ArchivesViewController(IntPtr handle) : base(handle) { }

		public override void LoadView()
		{
			base.LoadView();
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			NavigationItem.Title = Constants.__TITLE_ARCHIVES__;
		}
	}
}
