// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Archives.ViewControllers
{
	public partial class GroupPersonCVC : UICollectionViewCell
	{
		public UIImageView PersonImage => imageView;

		public UILabel PersonName => label;

		public GroupPersonCVC(IntPtr handle) : base(handle) { }
	}
}
