// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;
using System.Linq;
using System.Threading.Tasks;
using LocalAuthentication;
using Archives.Storage;
using AudioToolbox;

namespace Archives.ViewControllers
{
	public partial class LoginViewController : UIViewController
	{
		private bool _isPasscodeEnabled = false;

		public LoginViewController(IntPtr handle) : base(handle) { }

		public override void LoadView()
		{
			base.LoadView();
			_isPasscodeEnabled = Settings.BoolForKey(Constants.__SECURITY_ISPASSCODEENABLED__);

			if (!_isPasscodeEnabled)
			{
				HideFields();

				//go to initial page
				UIViewController uiview = Storyboard.InstantiateViewController("MainViewController");
				PresentViewController(uiview, false, null);
			}
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			if (_isPasscodeEnabled)
			{
				digits[0].BecomeFirstResponder();
				var isTouchIDEnabled = Settings.BoolForKey(Constants.__SECURITY_ISTOUCHIDENABLED__);

				if (isTouchIDEnabled)
					LaunchTouchID();
			}
		}

		private void HideFields()
		{
			this.View.BackgroundColor = UIColor.White;
			loginTitle.Hidden = true;
			foreach (UITextField t in digits)
				t.Hidden = true;
		}

		void LaunchTouchID()
		{
			var context = new LAContext();
			NSError AuthError;
			var reason = new NSString("Security validation");

			if (context.CanEvaluatePolicy(LAPolicy.DeviceOwnerAuthenticationWithBiometrics, out AuthError))
			{
				var replyHandler = new LAContextReplyHandler((success, error) =>
				{
					this.InvokeOnMainThread(() =>
					{
						if (success)
						{
							//go to initial page
							UIViewController uiview = Storyboard.InstantiateViewController("MainViewController");
							PresentViewController(uiview, false, null);
						}
					});

				});
				context.EvaluatePolicy(LAPolicy.DeviceOwnerAuthenticationWithBiometrics, reason, replyHandler);
			}
		}

		partial void digitEditingChanged(UITextField sender)
		{
			var nextDigit = digits.FirstOrDefault(tf => tf.Tag == sender.Tag + 1);

			if (nextDigit != null)
			{
				nextDigit.BecomeFirstResponder();
			}
			else
			{
				Task.Run(() =>
				{
					string opasscode = Keychain.GetItemFromKeychain(Keychain.AuthService).PrivateKey;
					string rpasscode = string.Empty;

					BeginInvokeOnMainThread(() =>
					{
						//backup second passcode and clear fields
						foreach (UITextField t in digits)
						{
							rpasscode += t.Text;
							t.Text = string.Empty;
						}

						//validate passcodes
						if (opasscode != rpasscode)
						{
							nextDigit = digits.FirstOrDefault();
							nextDigit.BecomeFirstResponder();
							rpasscode = string.Empty;
							SystemSound.Vibrate.PlayAlertSound();
						}
						else
						{
							//go to initial page
							UIViewController uiview = Storyboard.InstantiateViewController("MainViewController");
							PresentViewController(uiview, false, null);
						}
					});
				});
			}
		}

		partial void digitEditingDidBegin(UITextField sender)
		{
			sender.Text = string.Empty;
		}

		[Export("textField:shouldChangeCharactersInRange:replacementString:")]
		public bool ShouldChangeCharacters(UITextField textField, NSRange range, string replacementString)
		{
			var newLength = textField.Text.Length + replacementString.Length - range.Length;
			return newLength <= 1;
		}
	}
}
