// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Archives
{
	public partial class MainViewController : UITabBarController
	{
		public MainViewController (IntPtr handle) : base (handle){ }
	}
}
