// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Archives.ViewControllers
{
	public partial class PeopleViewController : UIViewController
	{
		public PeopleViewController(IntPtr handle) : base(handle) { }

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			this.Title = Constants.__TITLE_PEOPLE__;
		}
	}
}
