// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using System.Collections.Generic;
using Archives.Models;
using Archives.Sources;
using NomadCode.UIExtensions;
using Archives.Storage;

namespace Archives.ViewControllers
{
	public partial class SettingsViewController : UITableViewController
	{
		private bool _isPasscodeEnabled = false;
		private List<Setting> settings = new List<Setting>();
		private UIAlertController alert = null;

		public SettingsViewController(IntPtr handle) : base(handle) { }

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			NavigationItem.Title = "Settings";
			settings.Add(new Setting("security_cell", "Security", "SecurityViewController"));
			var settingsSource = new SettingsTableSource(settings, this);
			settingsSource.ViewControllerEvent += ViewControllerEvent;
			SettingsTableView.Source = settingsSource;
			SettingsTableView.AllowsMultipleSelection = false;
		}

		public void ViewControllerEvent(object sender, Setting e)
		{
			try
			{
				_isPasscodeEnabled = Settings.BoolForKey("IsPasscodeEnabled");

				BeginInvokeOnMainThread(() =>
				{
					if ((e.Name == "Security") && (_isPasscodeEnabled))
					{
                        var validate = Storyboard.Instantiate<ValidatePasscodeViewController>();

						validate.TargetViewController = "SecurityViewController";
						validate.Navigation = NavigationController;
						PresentViewController(validate, true, null);
					}
					else
					{
						UIViewController uiviewcontroller = Storyboard.InstantiateViewController(e.TargetViewController);
						NavigationController.PushViewController(uiviewcontroller, true);
					}
				});
			}
			catch
			{
				alert = UIAlertController.Create("Oops!", "There was a problem redirecting to the view", UIAlertControllerStyle.Alert);
				alert.AddAction(UIAlertAction.Create("Accept", UIAlertActionStyle.Cancel, null));
				PresentViewController(alert, true, null);
			}
		}
	}
}
