// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using NomadCode.UIExtensions;
using Archives.Storage;
using Archives.TableViewCells;

namespace Archives.ViewControllers
{
	public partial class SettingsViewController : UITableViewController
	{
		private bool _isPasscodeEnabled = false;
		private List<string> Items { get; set; } = new List<string>();

		public SettingsViewController(IntPtr handle) : base(handle) { }

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			NavigationItem.Title = Constants.__TITLE_SETTINGS__;
			Items.Add("Security");
			Items.Add("About");
		}

		public override nint NumberOfSections(UITableView tableView) => 1;

		public override nint RowsInSection(UITableView tableView, nint section) => Items.Count;

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.Dequeue<SettingTableViewCell>(indexPath);
			var item = Items[indexPath.Row];

			cell.TextLabel.Text = item;

			return cell;
		}

		public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			if (indexPath.Row == 0)
			{
				_isPasscodeEnabled = Settings.BoolForKey(Constants.__SECURITY_ISPASSCODEENABLED__);
				if (_isPasscodeEnabled)
				{
					var validate = Storyboard.Instantiate<ValidatePasscodeViewController>();
					validate.TargetViewController = "SecurityViewController";
					validate.Navigation = NavigationController;
					PresentViewController(validate, true, null);
				}
				else
				{
					UIViewController uiview = Storyboard.InstantiateViewController("SecurityViewController");
					NavigationController.PushViewController(uiview, true);
				}
			}

			if (indexPath.Row == 1)
			{
				UIViewController uiview = Storyboard.InstantiateViewController("AboutViewController");
				NavigationController.PushViewController(uiview, true);
			}
		}
	}
}
