// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace FaceAPI.iOS.ViewControllers
{
	public partial class PersonDetailViewController : UIViewController
	{
		public PersonDetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
